# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Date article modified'),
        ),
    ]
